
from pathlib import Path

import joblib
import numpy as np
import pandas as pd


# ============================================================
# Model path
# ============================================================

MODEL_PATH = (
    Path(__file__).resolve().parent
    / "industrial_fire_classifier.joblib"
)


# ============================================================
# Load model bundle
# ============================================================

BUNDLE = joblib.load(
    MODEL_PATH
)


MODEL = BUNDLE["model"]

FEATURES = BUNDLE[
    "features"
]

MEDIANS = BUNDLE.get(
    "training_medians",
    {}
)


# ============================================================
# ML inference
# ============================================================

def classify_clusters_ml(
    cluster_features: pd.DataFrame,
) -> pd.DataFrame:
    """
    Run the trained Random Forest on cluster-level
    features generated by the production pipeline.

    Returns the original DataFrame plus:

        label
        model_confidence
    """

    result = cluster_features.copy()


    # --------------------------------------------------------
    # Empty input
    # --------------------------------------------------------

    if result.empty:

        result[
            "label"
        ] = pd.Series(
            dtype=str
        )

        result[
            "model_confidence"
        ] = pd.Series(
            dtype=float
        )

        return result


    # --------------------------------------------------------
    # Validate feature schema
    # --------------------------------------------------------

    missing = [
        feature
        for feature in FEATURES
        if feature not in result.columns
    ]


    if missing:

        raise ValueError(
            "Missing ML features: "
            + ", ".join(
                missing
            )
        )


    # --------------------------------------------------------
    # Select exact training features
    # --------------------------------------------------------

    X = result[
        FEATURES
    ].copy()


    # --------------------------------------------------------
    # Normalize invalid numeric values
    # --------------------------------------------------------

    X = X.replace(
        [
            np.inf,
            -np.inf,
        ],
        np.nan,
    )


    # --------------------------------------------------------
    # Apply training-time medians
    # --------------------------------------------------------

    for feature in FEATURES:

        median = MEDIANS.get(
            feature,
            0.0,
        )


        X[
            feature
        ] = (
            pd.to_numeric(
                X[feature],
                errors="coerce",
            )
            .fillna(
                median
            )
        )


    # --------------------------------------------------------
    # Prediction
    # --------------------------------------------------------

    result[
        "label"
    ] = MODEL.predict(
        X
    )


    # --------------------------------------------------------
    # Prediction confidence
    # --------------------------------------------------------

    if hasattr(
        MODEL,
        "predict_proba",
    ):

        probabilities = (
            MODEL.predict_proba(
                X
            )
        )

        result[
            "model_confidence"
        ] = probabilities.max(
            axis=1
        )

    else:

        result[
            "model_confidence"
        ] = 0.0


    return result
